#!/usr/bin/env bash

set -eo pipefail

# if git_dest_sha doesn't already exist look it up from the checkout step
if [[ -z "$GIT_DEST_SHA" ]]; then
    export GIT_DEST_SHA=`buildkite-agent meta-data get "GIT_DEST_SHA"`
fi

if [[ ! -z "$GIT_DEST_SHA" ]]; then
  export BUILDKITE_GIT_CLONE_FLAGS="-v --depth 1"
  export BUILDKITE_GIT_FETCH_FLAGS="-v --prune --depth 1"
elif [[ "$BUILDKITE_PULL_REQUEST" == "" || "$BUILDKITE_PULL_REQUEST" == "false" ]]; then
  if [[ "$BUILDKITE_BRANCH" == "$BUILDKITE_PIPELINE_DEFAULT_BRANCH" || "$BUILDKITE_BRANCH" == "release/"* || "$BUILDKITE_BRANCH" == "gh-readonly-queue/"* ]]; then
    export BUILDKITE_GIT_CLONE_FLAGS="-v --depth 2"
    export BUILDKITE_GIT_FETCH_FLAGS="-v --prune --depth 2"
  else
    echo "unknown branch, will perform a full checkout"
  fi
else
    export BUILDKITE_GIT_CLONE_FLAGS="-v --depth 1"
    export BUILDKITE_GIT_FETCH_FLAGS="-v --prune --depth 1"
fi

