#!/usr/bin/env bash

set -euo pipefail

if [[ "$BUILDKITE_PULL_REQUEST" == "" || "$BUILDKITE_PULL_REQUEST" == "false" ]]; then
  if [[ "$BUILDKITE_BRANCH" == "develop" || "$BUILDKITE_BRANCH" == "release/"* || "$BUILDKITE_BRANCH" == "gh-readonly-queue/"* ]]; then
    export BUILDKITE_GIT_CLONE_FLAGS="-v --depth 2"
    export BUILDKITE_GIT_FETCH_FLAGS="-v --prune --depth 2"
  else
    echo "unknown branch, will perform a full checkout"
  fi
else
    export BUILDKITE_GIT_CLONE_FLAGS="-v --depth 1"
    export BUILDKITE_GIT_FETCH_FLAGS="-v --prune --depth 1"
fi

